# remote_theme: devich/quick@0.0.1

title: Dunia dalam Kekuatan
description: Sebuah novel fantasi oleh I T Rerek

exclude:
  - GUIDE.md

collections:
  cerita:
    output: true
    sort_by: path

# Vercel

vercel:
  # enable vercel analytics
  analytics: true
